// <auto-generated />
using EsmoChamps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsmoChamps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251229171247_InitialChampionSchema")]
    partial class InitialChampionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EsmoChamps.Models.ChampType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChampTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artillery Mage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Burst Mage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bruiser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Defensive Tank"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Offensive Tank"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Battle Mage"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marksman"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Enchanter"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Catcher"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Diver"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Duelist"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacroMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacroMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MechanicsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MechanicsMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RangeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacticalMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacticalMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampTypeId");

                    b.HasIndex("RangeTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("EsmoChamps.Models.RangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RangeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Melee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ranged"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Top Lane"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jungle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mid Lane"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bot Lane"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Champion", b =>
                {
                    b.HasOne("EsmoChamps.Models.ChampType", "ChampType")
                        .WithMany()
                        .HasForeignKey("ChampTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsmoChamps.Models.RangeType", "RangeType")
                        .WithMany()
                        .HasForeignKey("RangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsmoChamps.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChampType");

                    b.Navigation("RangeType");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
