// <auto-generated />
using EsmoChamps.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EsmoChamps.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("EsmoChamps.Models.ChampType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ChampTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Artillery Mage"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Burst Mage"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bruiser"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Defensive Tank"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Offensive Tank"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Assassin"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Battle Mage"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Marksman"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Enchanter"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Catcher"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Diver"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Duelist"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Champion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChampTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MacroMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MacroMin")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MechanicsMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MechanicsMin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PowerCurveEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerCurveMid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PowerCurveStart")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RangeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacticalMax")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TacticalMin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ChampTypeId");

                    b.HasIndex("RangeTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("Champions");
                });

            modelBuilder.Entity("EsmoChamps.Models.ChampionStrength", b =>
                {
                    b.Property<int>("ChampionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StrengthTitleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChampionId", "StrengthTitleId");

                    b.HasIndex("StrengthTitleId");

                    b.ToTable("ChampionStrengths");
                });

            modelBuilder.Entity("EsmoChamps.Models.RangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RangeTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Melee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ranged"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Top Lane"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jungle"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mid Lane"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bot Lane"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Support"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.StrengthTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StrengthTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The ability to force a fight to start, usually by closing the gap quickly.",
                            Title = "Engage"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The ability to limit enemy movement or actions through stuns, slows or roots.",
                            Title = "Crowd Control"
                        },
                        new
                        {
                            Id = 3,
                            Description = "The ability to catch out a single enemy and eliminate them before a teamfight starts.",
                            Title = "Pick Potential"
                        },
                        new
                        {
                            Id = 4,
                            Description = "The ability to secure major objectives like Dragon, Baron or Ram.",
                            Title = "Objective Control"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Strength in large-scale 5v5 battles involving the entire team.",
                            Title = "Teamfight"
                        },
                        new
                        {
                            Id = 6,
                            Description = "The ability to deal significant damage to multiple targets simultaneously.",
                            Title = "Area Damage"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Strength in 1v1 combat scenarios against other heroes.",
                            Title = "Dueling"
                        },
                        new
                        {
                            Id = 8,
                            Description = "The speed at which the hero can kill jungle camps or minion waves.",
                            Title = "Clear Speed"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Strength in small-scale, chaotic fights (e.g. 2v2 or 3v3).",
                            Title = "Skirmishing"
                        },
                        new
                        {
                            Id = 10,
                            Description = "The ability to ambush enemies in their lanes to secure kills or advantages.",
                            Title = "Ganking"
                        },
                        new
                        {
                            Id = 11,
                            Description = "The ability to control space and deny enemies access to specific areas.",
                            Title = "Zoning"
                        },
                        new
                        {
                            Id = 12,
                            Description = "The ability to kill minion waves quickly to defend turrets or push lanes.",
                            Title = "Wave Clear"
                        },
                        new
                        {
                            Id = 13,
                            Description = "The ability to pressure enemy turrets and force enemies to defend under them.",
                            Title = "Siege"
                        },
                        new
                        {
                            Id = 14,
                            Description = "The ability to protect vulnerable allies by intercepting or disabling enemy divers.",
                            Title = "Peel"
                        },
                        new
                        {
                            Id = 15,
                            Description = "The ability to quickly move between lanes to impact other parts of the map.",
                            Title = "Roaming"
                        },
                        new
                        {
                            Id = 16,
                            Description = "The ability to apply pressure in a side lane alone while the team fights elsewhere.",
                            Title = "Split Push"
                        },
                        new
                        {
                            Id = 17,
                            Description = "The ability to chase down and finish off low-health enemies after a fight.",
                            Title = "Cleanup"
                        },
                        new
                        {
                            Id = 18,
                            Description = "The ability to deal damage from a long range without fully committing to a fight.",
                            Title = "Poke"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Strength in controlling the early laning phase and suppressing the opponent.",
                            Title = "Lane Dominance"
                        },
                        new
                        {
                            Id = 20,
                            Description = "The ability to convert an early lead into an unstoppable advantage.",
                            Title = "Snowball"
                        });
                });

            modelBuilder.Entity("EsmoChamps.Models.Champion", b =>
                {
                    b.HasOne("EsmoChamps.Models.ChampType", "ChampType")
                        .WithMany()
                        .HasForeignKey("ChampTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsmoChamps.Models.RangeType", "RangeType")
                        .WithMany()
                        .HasForeignKey("RangeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsmoChamps.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChampType");

                    b.Navigation("RangeType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EsmoChamps.Models.ChampionStrength", b =>
                {
                    b.HasOne("EsmoChamps.Models.Champion", "Champion")
                        .WithMany("Strengths")
                        .HasForeignKey("ChampionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsmoChamps.Models.StrengthTitle", "StrengthTitle")
                        .WithMany("ChampionStrengths")
                        .HasForeignKey("StrengthTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Champion");

                    b.Navigation("StrengthTitle");
                });

            modelBuilder.Entity("EsmoChamps.Models.Champion", b =>
                {
                    b.Navigation("Strengths");
                });

            modelBuilder.Entity("EsmoChamps.Models.StrengthTitle", b =>
                {
                    b.Navigation("ChampionStrengths");
                });
#pragma warning restore 612, 618
        }
    }
}
